DM-47210: Add analysis tasks to the injected RC2 pipelines.
lsst/drp_pipe pull request #174
Opened 2024-10-30 18:11 UTC by jtmccann

2024-11-07 20:55 UTC, taranu approved these changes

2025-02-14 00:18 UTC, taranu requested changes
In general I think this looks good (if it works, it works!), and I'm okay to have this go in before the DC2-based injection, but I think there are some things we'll want to pre-emptively specify stars or bright stars in the names for so they don't clash with future injection pipelines/tasks. I'm pinging @leeskelvin for thoughts on that.

2025-02-14 00:18 UTC, taranu commented on pipelines/LSSTComCam/DRP-post-injected.yaml
> +          bands_color = {"u", "g", "r", "i", "z", "y"},
This should be okay to omit since ugrizy is the default.

2025-02-14 00:18 UTC, taranu commented on pipelines/LSSTComCam/DRP-post-injected.yaml
> +      columns_target_copy: [
I think I forgot `objectId` here.

2025-02-14 00:18 UTC, taranu commented on SConstruct
> +    "DRP-RC2-post-injected.yaml",
Can we append `-brightstars` to this? Or `bright-stars`? Whatever we want to call this (@leeskelvin ?).

2025-02-14 00:18 UTC, taranu commented on SConstruct
> +    "DRP-post-injected.yaml",
Same here, add `-brightstars`.

2025-02-14 00:18 UTC, taranu commented on pipelines/HSC/DRP-RC2-post-injected.yaml
> +  compare_object_to_injected:
`compare_object_to_injected_bright_stars`?

2025-02-14 00:18 UTC, taranu commented on pipelines/HSC/DRP-RC2-post-injected.yaml
> +  diff_matched_analysis:
I think it's time to give this a better name too - `analyze_matched_injected_bright_stars`?

2025-02-14 00:18 UTC, taranu commented on SConstruct
> +subset_name = "injected_coadd_analysis"
Maybe `injected_bright_stars_coadd_analysis`?

2025-02-17 18:05 UTC, jtmccann commented on SConstruct
> +    "DRP-RC2-post-injected.yaml",
Could these post-injected pipelines be generalized to be used for any kind of injection? Rather than making multiple different post-injected pipelines with slightly different configs. For example, if we wanted to do galaxy injections what additional columns would we need? If it's just a few then it might be easier just to include them by default for generality's sake.

2025-02-19 03:52 UTC, taranu commented on SConstruct
> +    "DRP-RC2-post-injected.yaml",
Hmm... not really. See the [equivalent file I made](https://github.com/lsst-sitcom/sciunit_galaxies/blob/a7316be59e4a694dc019e9607e97ff4e3976d904/pipelines/DRP-post-DC2-injected.yaml) for galaxy injection. We can harmonize the copied columns without doing any harm (besides bloating the matched tables, but it's conceivable we still might want to look at model/aperture mags for stars) but there are more config changes than just that.  The consolidate task needs to have added columns for galaxy parameters that won't exist in injection catalogs with just stars. The analysis task could make the same plots/metrics but if you're only injecting stars then the ones for reference galaxies will be empty/useless and the ones for reference objects of all types will be identical to the ones for stars alone.

2025-02-19 20:26 UTC, leeskelvin commented on SConstruct
> +    "DRP-RC2-post-injected.yaml",
I can certainly see the merit for somehow distinguishing between the bright-star flavor and the galaxy flavor of these injection YAMLs. I'm not sure if `bright-stars` is sufficient long-term, as we may have another "bright stars" catalog that we want to inject down the line. Perhaps we need to embed the `DM-NNNNN` name that corresponds to the recommended input injection catalog?

Or, rather than "bright stars", if this injection YAML is instead suitable for all "stars only" injection catalogs, then lets just append `-stars`? That would mean that the ultimate final user-facing YAML would be named, e.g., `DRP-RC2_subset+injected_deepCoadd-stars.yaml`.

Naming things is hard (TM), so for now, I propose that we append `-stars` to this catalog and `-galaxies` to the future galaxies catalog. Longer-term, we may have to loop back to derive a better and more concise naming scheme.

2025-02-20 20:50 UTC, taranu commented on SConstruct
> +    "DRP-RC2-post-injected.yaml",
I'm fine with `-stars`. The pipeline itself should presumably work with any kind of injection catalog with stars in it.

`galaxies` is also fine for now, I suppose. The pipeline would need to change if it's only galaxies vs galaxies + stars. For now we can document that users should include stars too - galaxy photometry algorithms don't necessarily need to perform very well on stars but they should at least not fail and ideally not be much worse than PSF mags for anyone doing a homogeneous selection/running classifiers.

If/when we get around to injecting non-parametric galaxies (or a mix of both) we might need to tweak things further.

2025-02-25 21:16 UTC, jtmccann commented on pipelines/HSC/DRP-RC2-post-injected.yaml
> +  compare_object_to_injected:
I tried changing the task names and got an error about the same dataset type being the output of two different tasks. I decided to revert the task name change since there are only config differences between a star vs galaxy run. I don't think a star run is fundamentally different from a galaxy run, so they ought to keep the same dataset type and task names.

I will however keep the "-post-injected-stars" names for the YAMLs to differentiate the star configs from any future galaxy config files.

Let me know what you think. Thanks!

2025-02-26 18:06 UTC, taranu approved these changes

2025-02-26 21:53 UTC, merged